waitfor-connection:
  build: .
  links:
    - tcp-server
  volumes:
    - .:/usr/src/app
  command: npm test

tcp-server:
  image: gophernet/netcat
  expose:
    - "9000"
  # http://www.comrite.com/dict/man.php/man/mini-netcat/nc
  # https://busybox.net/downloads/BusyBox.html#nc
  command: -lk -vv -p 9000 -e '/bin/sh'
